(()=>{
  const $=id=>document.getElementById(id),stages=[...document.querySelectorAll('.reading-stage')];
  const positions=[['过去','Past','它可能留下了什么影响？'],['现在','Present','它怎样描述此刻？'],['未来','Future','它可能带来什么趋势？']];
  let deckOrder=[],cards=[],notes=['','',''],methods=['','',''],interpretIndex=0,fanCenter=0,selectedCardId=null,pointer=null,wheelTimer=0;
  const show=id=>stages.forEach(stage=>stage.hidden=stage.id!==id);
  function config(){const d=DECKS.find(x=>x.name==='维特塔罗')||DECKS[0];return{path:d.path.replace(/\/+$/,''),format:d.format||'png',back:d.backFile||'back.png',startAt:Number(d.startAt)||0,count:Number(d.cardCount)||78}}
  const cardPath=id=>{const d=config();return`${d.path}/${d.startAt+id}.${d.format}`},backPath=()=>{const d=config();return`${d.path}/${d.back}`},identity=id=>TAROT_CARDS.find(card=>card.id===id);
  const clampCenter=value=>Math.max(0,Math.min(deckOrder.length-1,value));
  const escapeHtml=value=>String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  function shuffle(){const ids=Array.from({length:config().count},(_,i)=>i);for(let i=ids.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[ids[i],ids[j]]=[ids[j],ids[i]]}return ids}
  function flipper(item){return`<div class="card-flipper"><div class="card-face card-back"><img src="${backPath()}" alt="牌背"></div><div class="card-face card-front ${item.orientation==='reversed'?'reversed':''}"><img src="${cardPath(item.id)}" alt="${identity(item.id).nameZh}"></div></div>`}
  function boardMarkup(reveal=false){return positions.map((p,i)=>{const item=cards[i];return`<div class="card-slot ${!reveal&&i===cards.length?'current':''}"><div class="${reveal?'reading-card':'slot-frame'} ${item?'filled':''}" data-number="${i+1}" data-index="${i}">${item?(reveal?flipper(item):`<img src="${backPath()}" alt="牌背">`):''}</div><strong>${p[0]}</strong><small>${p[1]}</small></div>`}).join('')}
  function renderBoard(){$('spreadBoard').innerHTML=boardMarkup(false);$('drawHint').textContent=cards.length<3?`为「${positions[cards.length][0]}」抽一张牌。`:'三张牌已经进入牌阵。'}
  function renderFan(){
    const wrap=$('fanWrap');if(!deckOrder.length){wrap.innerHTML='';return}fanCenter=clampCenter(fanCenter);
    const nearest=Math.round(fanCenter),half=7,lo=Math.max(0,nearest-half),hi=Math.min(deckOrder.length-1,nearest+half);let html='';
    for(let i=lo;i<=hi;i++){const id=deckOrder[i],selected=id===selectedCardId,rel=i-fanCenter,abs=Math.abs(rel),x=rel*32,y=Math.pow(abs,1.55)*4.1-(selected?34:0),angle=rel*5.2,scale=Math.max(.84,1-abs*.018)+(selected ? .055 : 0),opacity=Math.max(.35,1-abs*.075);html+=`<button class="fan-card ${abs<=.5?'is-center':''} ${selected?'preselected':''}" type="button" data-id="${id}" data-index="${i}" aria-label="${selected?'再次点击抽取':'选中这张牌'}" style="transform:translateX(calc(-50% + ${x}px)) translateY(${y}px) rotate(${angle}deg) scale(${scale});opacity:${opacity};z-index:${selected?130:100-Math.round(abs)}"><img src="${backPath()}" alt=""></button>`}
    wrap.innerHTML=html;
  }
  function settleFan(){fanCenter=clampCenter(Math.round(fanCenter));renderFan()}
  function fly(source,target,done){const a=source.getBoundingClientRect(),b=target.getBoundingClientRect(),clone=source.cloneNode(true);clone.className='fan-card flying-card';clone.style.cssText=`left:${a.left}px;top:${a.top}px;bottom:auto;width:${a.width}px;height:${a.height}px;transform:none;opacity:1`;document.body.append(clone);requestAnimationFrame(()=>{clone.style.left=`${b.left}px`;clone.style.top=`${b.top}px`;clone.style.width=`${b.width}px`;clone.style.height=`${b.height}px`;clone.style.transform='rotate(0deg)'});setTimeout(()=>{clone.remove();done()},470)}
  function choose(button){if(cards.length>=3||!button||button.disabled)return;button.disabled=true;const id=Number(button.dataset.id),orientation=Math.random()<.5?'upright':'reversed',target=$('spreadBoard').querySelectorAll('.slot-frame')[cards.length];new Image().src=cardPath(id);fly(button,target,()=>{const removedIndex=deckOrder.indexOf(id);cards.push({id,orientation});deckOrder=deckOrder.filter(x=>x!==id);if(removedIndex<=fanCenter)fanCenter=Math.max(0,fanCenter-1);renderBoard();if(cards.length===3)setTimeout(openReveal,260);else renderFan()})}
  function tapCard(cardId){const index=deckOrder.indexOf(cardId);if(index<0)return;if(selectedCardId===cardId){choose($('fanWrap').querySelector(`[data-id="${cardId}"]`));selectedCardId=null;return}selectedCardId=cardId;fanCenter=index;renderFan()}
  function bindFanGestures(){
    const wrap=$('fanWrap');
    wrap.addEventListener('pointerdown',e=>{const rect=wrap.getBoundingClientRect(),relativeX=e.clientX-(rect.left+rect.width/2),index=Math.max(0,Math.min(deckOrder.length-1,Math.round(fanCenter+relativeX/32)));pointer={id:e.pointerId,startX:e.clientX,startCenter:fanCenter,moved:false,cardId:deckOrder[index]??null};wrap.setPointerCapture(e.pointerId);wrap.classList.add('dragging');e.preventDefault()});
    wrap.addEventListener('pointermove',e=>{if(!pointer||pointer.id!==e.pointerId)return;const dx=e.clientX-pointer.startX;if(Math.abs(dx)>7){pointer.moved=true;selectedCardId=null}fanCenter=clampCenter(pointer.startCenter-dx/31);renderFan()});
    const finish=e=>{if(!pointer||pointer.id!==e.pointerId)return;const wasTap=!pointer.moved,cardId=pointer.cardId;pointer=null;wrap.classList.remove('dragging');if(wasTap&&cardId!==null)tapCard(cardId);else settleFan()};
    wrap.addEventListener('pointerup',finish);wrap.addEventListener('pointercancel',finish);
    wrap.addEventListener('wheel',e=>{e.preventDefault();fanCenter=clampCenter(fanCenter+(Math.abs(e.deltaX)>Math.abs(e.deltaY)?e.deltaX:e.deltaY)/65);renderFan();clearTimeout(wheelTimer);wheelTimer=setTimeout(settleFan,130)},{passive:false});
    wrap.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.matches('.fan-card')){e.preventDefault();tapCard(Number(e.target.dataset.id))}});
  }
  function openReveal(){$('revealBoard').innerHTML=boardMarkup(true);$('revealBoard').querySelectorAll('.reading-card').forEach(card=>card.addEventListener('click',()=>{card.classList.add('revealed');card.dataset.open='1';if($('revealBoard').querySelectorAll('[data-open="1"]').length===cards.length)$('beginInterpret').disabled=false}));show('reveal')}
  function referenceFor(item,index){const content=TAROT_DAILY_CONTENT.find(x=>x.id===item.id),core=content?.[item.orientation]?.core||'这张牌的参考内容仍在整理中。';const lead=['放在「过去」，它可以帮助你回看这股能量怎样影响了现在。','放在「现在」，它把注意力带回此刻正在发生的状态。','放在「未来」，它描述的是沿着当前方向可能延伸的趋势。'][index];return`${lead}${core}`}
  function selectMethod(method){methods[interpretIndex]=method;$('selfPanel').hidden=method!=='self';$('referencePanel').hidden=method!=='reference';document.querySelectorAll('.interpret-methods button').forEach(button=>button.classList.toggle('selected',button.dataset.method===method));if(method==='reference'){notes[interpretIndex]=referenceFor(cards[interpretIndex],interpretIndex);$('positionReference').textContent=notes[interpretIndex];$('nextInterpret').disabled=false}else{$('positionNote').value=notes[interpretIndex];$('nextInterpret').disabled=!$('positionNote').value.trim()}}
  function renderInterpret(){const item=cards[interpretIndex],p=positions[interpretIndex],x=identity(item.id);$('positionEn').textContent=p[1];$('positionZh').textContent=p[0];$('cardName').textContent=x.nameZh;$('positionPrompt').textContent=p[2];$('orientation').textContent=item.orientation==='upright'?'正位':'逆位';$('interpretCard').innerHTML=flipper(item);$('positionNote').value=methods[interpretIndex]==='self'?notes[interpretIndex]:'';$('nextInterpret').textContent=interpretIndex===2?'整理这次解读':`继续到${positions[interpretIndex+1][0]}`;$('nextInterpret').disabled=true;$('selfPanel').hidden=true;$('referencePanel').hidden=true;document.querySelectorAll('.interpret-methods button').forEach(button=>button.classList.remove('selected'));show('interpret');if(methods[interpretIndex])selectMethod(methods[interpretIndex])}
  function renderReview(){$('reviewQuestion').textContent=$('question').value.trim()?`问题：${$('question').value.trim()}`:'这次没有写下具体问题。';$('readingReviewList').innerHTML=cards.map((item,i)=>`<article class="reading-review-item"><strong>${positions[i][0]} · ${identity(item.id).nameZh}</strong><small>${item.orientation==='upright'?'正位':'逆位'} · ${methods[i]==='reference'?'参考解读':'我的理解'}</small><p>${escapeHtml(notes[i])}</p></article>`).join('');show('readingReview')}
  function save(){const key='magic_u_reading_records_v1',records=(()=>{try{const x=JSON.parse(localStorage.getItem(key)||'[]');return Array.isArray(x)?x:[]}catch{return[]}})();records.unshift({id:`reading-${Date.now()}`,createdAt:new Date().toISOString(),spreadId:'time',spreadTitle:'时间之流',question:$('question').value.trim(),cards:cards.map((item,i)=>({...item,position:positions[i][0],nameZh:identity(item.id).nameZh,nameEn:identity(item.id).nameEn})),answers:[...notes],answerMethods:[...methods]});localStorage.setItem(key,JSON.stringify(records.slice(0,100)))}
  function start(){deckOrder=shuffle();cards=[];notes=['','',''];methods=['','',''];interpretIndex=0;selectedCardId=null;fanCenter=(deckOrder.length-1)/2;renderBoard();renderFan();show('draw')}
  bindFanGestures();$('startDraw').onclick=start;$('beginInterpret').onclick=()=>{interpretIndex=0;renderInterpret()};document.querySelector('.interpret-methods').onclick=e=>{const button=e.target.closest('[data-method]');if(button)selectMethod(button.dataset.method)};$('positionNote').oninput=()=>{$('nextInterpret').disabled=!$('positionNote').value.trim()};$('nextInterpret').onclick=()=>{if(methods[interpretIndex]==='self')notes[interpretIndex]=$('positionNote').value.trim();if(!notes[interpretIndex])return;if(interpretIndex<2){interpretIndex++;renderInterpret()}else renderReview()};$('saveReading').onclick=()=>{save();show('done')};$('again').onclick=()=>{$('question').value='';show('intro')};show('intro');
})();
