/** Rider–Waite tarot identity data only. No meanings or interpretations. */
const TAROT_CARDS = window.TAROT_CARDS = [
  { id: 0, file: '0.png', nameZh: '愚人', nameEn: 'The Fool', arcana: 'major', element: null, suit: null, rank: 0 },
  { id: 1, file: '1.png', nameZh: '魔术师', nameEn: 'The Magician', arcana: 'major', element: null, suit: null, rank: 1 },
  { id: 2, file: '2.png', nameZh: '女祭司', nameEn: 'The High Priestess', arcana: 'major', element: null, suit: null, rank: 2 },
  { id: 3, file: '3.png', nameZh: '皇后', nameEn: 'The Empress', arcana: 'major', element: null, suit: null, rank: 3 },
  { id: 4, file: '4.png', nameZh: '皇帝', nameEn: 'The Emperor', arcana: 'major', element: null, suit: null, rank: 4 },
  { id: 5, file: '5.png', nameZh: '教皇', nameEn: 'The Hierophant', arcana: 'major', element: null, suit: null, rank: 5 },
  { id: 6, file: '6.png', nameZh: '恋人', nameEn: 'The Lovers', arcana: 'major', element: null, suit: null, rank: 6 },
  { id: 7, file: '7.png', nameZh: '战车', nameEn: 'The Chariot', arcana: 'major', element: null, suit: null, rank: 7 },
  { id: 8, file: '8.png', nameZh: '力量', nameEn: 'Strength', arcana: 'major', element: null, suit: null, rank: 8 },
  { id: 9, file: '9.png', nameZh: '隐者', nameEn: 'The Hermit', arcana: 'major', element: null, suit: null, rank: 9 },
  { id: 10, file: '10.png', nameZh: '命运之轮', nameEn: 'Wheel of Fortune', arcana: 'major', element: null, suit: null, rank: 10 },
  { id: 11, file: '11.png', nameZh: '正义', nameEn: 'Justice', arcana: 'major', element: null, suit: null, rank: 11 },
  { id: 12, file: '12.png', nameZh: '倒吊人', nameEn: 'The Hanged Man', arcana: 'major', element: null, suit: null, rank: 12 },
  { id: 13, file: '13.png', nameZh: '死神', nameEn: 'Death', arcana: 'major', element: null, suit: null, rank: 13 },
  { id: 14, file: '14.png', nameZh: '节制', nameEn: 'Temperance', arcana: 'major', element: null, suit: null, rank: 14 },
  { id: 15, file: '15.png', nameZh: '恶魔', nameEn: 'The Devil', arcana: 'major', element: null, suit: null, rank: 15 },
  { id: 16, file: '16.png', nameZh: '高塔', nameEn: 'The Tower', arcana: 'major', element: null, suit: null, rank: 16 },
  { id: 17, file: '17.png', nameZh: '星星', nameEn: 'The Star', arcana: 'major', element: null, suit: null, rank: 17 },
  { id: 18, file: '18.png', nameZh: '月亮', nameEn: 'The Moon', arcana: 'major', element: null, suit: null, rank: 18 },
  { id: 19, file: '19.png', nameZh: '太阳', nameEn: 'The Sun', arcana: 'major', element: null, suit: null, rank: 19 },
  { id: 20, file: '20.png', nameZh: '审判', nameEn: 'Judgement', arcana: 'major', element: null, suit: null, rank: 20 },
  { id: 21, file: '21.png', nameZh: '世界', nameEn: 'The World', arcana: 'major', element: null, suit: null, rank: 21 },

  { id: 22, file: '22.png', nameZh: '宝剑王牌', nameEn: 'Ace of Swords', arcana: 'minor', element: 'air', suit: 'swords', rank: 'ace' },
  { id: 23, file: '23.png', nameZh: '宝剑二', nameEn: 'Two of Swords', arcana: 'minor', element: 'air', suit: 'swords', rank: 2 },
  { id: 24, file: '24.png', nameZh: '宝剑三', nameEn: 'Three of Swords', arcana: 'minor', element: 'air', suit: 'swords', rank: 3 },
  { id: 25, file: '25.png', nameZh: '宝剑四', nameEn: 'Four of Swords', arcana: 'minor', element: 'air', suit: 'swords', rank: 4 },
  { id: 26, file: '26.png', nameZh: '宝剑五', nameEn: 'Five of Swords', arcana: 'minor', element: 'air', suit: 'swords', rank: 5 },
  { id: 27, file: '27.png', nameZh: '宝剑六', nameEn: 'Six of Swords', arcana: 'minor', element: 'air', suit: 'swords', rank: 6 },
  { id: 28, file: '28.png', nameZh: '宝剑七', nameEn: 'Seven of Swords', arcana: 'minor', element: 'air', suit: 'swords', rank: 7 },
  { id: 29, file: '29.png', nameZh: '宝剑八', nameEn: 'Eight of Swords', arcana: 'minor', element: 'air', suit: 'swords', rank: 8 },
  { id: 30, file: '30.png', nameZh: '宝剑九', nameEn: 'Nine of Swords', arcana: 'minor', element: 'air', suit: 'swords', rank: 9 },
  { id: 31, file: '31.png', nameZh: '宝剑十', nameEn: 'Ten of Swords', arcana: 'minor', element: 'air', suit: 'swords', rank: 10 },
  { id: 32, file: '32.png', nameZh: '宝剑侍从', nameEn: 'Page of Swords', arcana: 'minor', element: 'air', suit: 'swords', rank: 'page' },
  { id: 33, file: '33.png', nameZh: '宝剑骑士', nameEn: 'Knight of Swords', arcana: 'minor', element: 'air', suit: 'swords', rank: 'knight' },
  { id: 34, file: '34.png', nameZh: '宝剑王后', nameEn: 'Queen of Swords', arcana: 'minor', element: 'air', suit: 'swords', rank: 'queen' },
  { id: 35, file: '35.png', nameZh: '宝剑国王', nameEn: 'King of Swords', arcana: 'minor', element: 'air', suit: 'swords', rank: 'king' },

  { id: 36, file: '36.png', nameZh: '权杖王牌', nameEn: 'Ace of Wands', arcana: 'minor', element: 'fire', suit: 'wands', rank: 'ace' },
  { id: 37, file: '37.png', nameZh: '权杖二', nameEn: 'Two of Wands', arcana: 'minor', element: 'fire', suit: 'wands', rank: 2 },
  { id: 38, file: '38.png', nameZh: '权杖三', nameEn: 'Three of Wands', arcana: 'minor', element: 'fire', suit: 'wands', rank: 3 },
  { id: 39, file: '39.png', nameZh: '权杖四', nameEn: 'Four of Wands', arcana: 'minor', element: 'fire', suit: 'wands', rank: 4 },
  { id: 40, file: '40.png', nameZh: '权杖五', nameEn: 'Five of Wands', arcana: 'minor', element: 'fire', suit: 'wands', rank: 5 },
  { id: 41, file: '41.png', nameZh: '权杖六', nameEn: 'Six of Wands', arcana: 'minor', element: 'fire', suit: 'wands', rank: 6 },
  { id: 42, file: '42.png', nameZh: '权杖七', nameEn: 'Seven of Wands', arcana: 'minor', element: 'fire', suit: 'wands', rank: 7 },
  { id: 43, file: '43.png', nameZh: '权杖八', nameEn: 'Eight of Wands', arcana: 'minor', element: 'fire', suit: 'wands', rank: 8 },
  { id: 44, file: '44.png', nameZh: '权杖九', nameEn: 'Nine of Wands', arcana: 'minor', element: 'fire', suit: 'wands', rank: 9 },
  { id: 45, file: '45.png', nameZh: '权杖十', nameEn: 'Ten of Wands', arcana: 'minor', element: 'fire', suit: 'wands', rank: 10 },
  { id: 46, file: '46.png', nameZh: '权杖侍从', nameEn: 'Page of Wands', arcana: 'minor', element: 'fire', suit: 'wands', rank: 'page' },
  { id: 47, file: '47.png', nameZh: '权杖骑士', nameEn: 'Knight of Wands', arcana: 'minor', element: 'fire', suit: 'wands', rank: 'knight' },
  { id: 48, file: '48.png', nameZh: '权杖王后', nameEn: 'Queen of Wands', arcana: 'minor', element: 'fire', suit: 'wands', rank: 'queen' },
  { id: 49, file: '49.png', nameZh: '权杖国王', nameEn: 'King of Wands', arcana: 'minor', element: 'fire', suit: 'wands', rank: 'king' },

  { id: 50, file: '50.png', nameZh: '圣杯王牌', nameEn: 'Ace of Cups', arcana: 'minor', element: 'water', suit: 'cups', rank: 'ace' },
  { id: 51, file: '51.png', nameZh: '圣杯二', nameEn: 'Two of Cups', arcana: 'minor', element: 'water', suit: 'cups', rank: 2 },
  { id: 52, file: '52.png', nameZh: '圣杯三', nameEn: 'Three of Cups', arcana: 'minor', element: 'water', suit: 'cups', rank: 3 },
  { id: 53, file: '53.png', nameZh: '圣杯四', nameEn: 'Four of Cups', arcana: 'minor', element: 'water', suit: 'cups', rank: 4 },
  { id: 54, file: '54.png', nameZh: '圣杯五', nameEn: 'Five of Cups', arcana: 'minor', element: 'water', suit: 'cups', rank: 5 },
  { id: 55, file: '55.png', nameZh: '圣杯六', nameEn: 'Six of Cups', arcana: 'minor', element: 'water', suit: 'cups', rank: 6 },
  { id: 56, file: '56.png', nameZh: '圣杯七', nameEn: 'Seven of Cups', arcana: 'minor', element: 'water', suit: 'cups', rank: 7 },
  { id: 57, file: '57.png', nameZh: '圣杯八', nameEn: 'Eight of Cups', arcana: 'minor', element: 'water', suit: 'cups', rank: 8 },
  { id: 58, file: '58.png', nameZh: '圣杯九', nameEn: 'Nine of Cups', arcana: 'minor', element: 'water', suit: 'cups', rank: 9 },
  { id: 59, file: '59.png', nameZh: '圣杯十', nameEn: 'Ten of Cups', arcana: 'minor', element: 'water', suit: 'cups', rank: 10 },
  { id: 60, file: '60.png', nameZh: '圣杯侍从', nameEn: 'Page of Cups', arcana: 'minor', element: 'water', suit: 'cups', rank: 'page' },
  { id: 61, file: '61.png', nameZh: '圣杯骑士', nameEn: 'Knight of Cups', arcana: 'minor', element: 'water', suit: 'cups', rank: 'knight' },
  { id: 62, file: '62.png', nameZh: '圣杯王后', nameEn: 'Queen of Cups', arcana: 'minor', element: 'water', suit: 'cups', rank: 'queen' },
  { id: 63, file: '63.png', nameZh: '圣杯国王', nameEn: 'King of Cups', arcana: 'minor', element: 'water', suit: 'cups', rank: 'king' },

  { id: 64, file: '64.png', nameZh: '星币王牌', nameEn: 'Ace of Pentacles', arcana: 'minor', element: 'earth', suit: 'pentacles', rank: 'ace' },
  { id: 65, file: '65.png', nameZh: '星币二', nameEn: 'Two of Pentacles', arcana: 'minor', element: 'earth', suit: 'pentacles', rank: 2 },
  { id: 66, file: '66.png', nameZh: '星币三', nameEn: 'Three of Pentacles', arcana: 'minor', element: 'earth', suit: 'pentacles', rank: 3 },
  { id: 67, file: '67.png', nameZh: '星币四', nameEn: 'Four of Pentacles', arcana: 'minor', element: 'earth', suit: 'pentacles', rank: 4 },
  { id: 68, file: '68.png', nameZh: '星币五', nameEn: 'Five of Pentacles', arcana: 'minor', element: 'earth', suit: 'pentacles', rank: 5 },
  { id: 69, file: '69.png', nameZh: '星币六', nameEn: 'Six of Pentacles', arcana: 'minor', element: 'earth', suit: 'pentacles', rank: 6 },
  { id: 70, file: '70.png', nameZh: '星币七', nameEn: 'Seven of Pentacles', arcana: 'minor', element: 'earth', suit: 'pentacles', rank: 7 },
  { id: 71, file: '71.png', nameZh: '星币八', nameEn: 'Eight of Pentacles', arcana: 'minor', element: 'earth', suit: 'pentacles', rank: 8 },
  { id: 72, file: '72.png', nameZh: '星币九', nameEn: 'Nine of Pentacles', arcana: 'minor', element: 'earth', suit: 'pentacles', rank: 9 },
  { id: 73, file: '73.png', nameZh: '星币十', nameEn: 'Ten of Pentacles', arcana: 'minor', element: 'earth', suit: 'pentacles', rank: 10 },
  { id: 74, file: '74.png', nameZh: '星币侍从', nameEn: 'Page of Pentacles', arcana: 'minor', element: 'earth', suit: 'pentacles', rank: 'page' },
  { id: 75, file: '75.png', nameZh: '星币骑士', nameEn: 'Knight of Pentacles', arcana: 'minor', element: 'earth', suit: 'pentacles', rank: 'knight' },
  { id: 76, file: '76.png', nameZh: '星币王后', nameEn: 'Queen of Pentacles', arcana: 'minor', element: 'earth', suit: 'pentacles', rank: 'queen' },
  { id: 77, file: '77.png', nameZh: '星币国王', nameEn: 'King of Pentacles', arcana: 'minor', element: 'earth', suit: 'pentacles', rank: 'king' }
];
